#baseURL = 'https://tunalad.indie.af/'
baseURL = 'https://tunalad.github.io/'
languageCode = 'en-us'
title = "Novica's Website"

uglyURLs = false

[params]
    lightswitch = false
    footer = "&copy; Novica {Year}"

[taxonomies]
    tag = "tags"
    tech = "tech"

[permalinks]
    tags = "/tags/:slug/"

#theme = "hugo-classic"
#theme = "no-style-please"
#theme = "kaslaanka"
#theme = "tunalad-portfolio"
#theme = "hugo-xmin"
#theme = "hugo-xterm"

[[menu.main]]
name = "Home"
url = "/"
weight = 10
[[menu.main]]
name = "About"
url = "/about"
weight = 20
[[menu.main]]
name = "Projects"
url = "/projects"
weight = 30
[[menu.main]]
name = "Contact"
url = "mailto:arsic.novica00@gmail.com"
weight = 9999999
